// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/vakeel-features/FeatureCards.tsx": () => import("../components/mockups/vakeel-features/FeatureCards.tsx"),
  "./components/mockups/vakeel-hero/HeroRedesign.tsx": () => import("../components/mockups/vakeel-hero/HeroRedesign.tsx"),
  "./components/mockups/vakeel-voice/VoiceDemo.tsx": () => import("../components/mockups/vakeel-voice/VoiceDemo.tsx")
};
